#ifndef INCLUDE_PRIORITIZEDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP
#define INCLUDE_PRIORITIZEDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP

namespace pgp
{

enum class ContinueOrBreak
{
  CONTINUE,
  BREAK
};

}

#endif // INCLUDE_PRIORITIZEDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP
