#ifndef INCLUDE_ORDEREDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP
#define INCLUDE_ORDEREDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP

namespace ogp
{

enum class ContinueOrBreak
{
  CONTINUE,
  BREAK
};

}

#endif // INCLUDE_ORDEREDGOALSPLANNER_UTIL_CONTINUEORBREAK_HPP
