#ifndef INCLUDE_CONTEXTUALPLANNER_UTIL_CONTINUEORBREAK_HPP
#define INCLUDE_CONTEXTUALPLANNER_UTIL_CONTINUEORBREAK_HPP

namespace cp
{

enum class ContinueOrBreak
{
  CONTINUE,
  BREAK
};

}

#endif // INCLUDE_CONTEXTUALPLANNER_UTIL_CONTINUEORBREAK_HPP
